app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'
urlpatterns=[
    path('func/', func, name='func'),

    path('fnc/',fnc, name='fnc'),
]

project5/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import *
import app2


urlpatterns = [
    path('admin/', admin.site.urls),
    path('h1/',h1,name='h1'),
    path('h2/',h2,name='h2'),
    path('app2/', include('app2.urls'))
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def h1(request):
    return render(request,'h1.html')
def h2(request):
    return render(request,'h2.html')    

app2/views.py
from django.shortcuts import render

def func(request):
    return render(request,'h1.html')

def fnc(request):
    return render(request,'h2.html')

templates/h1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>navigation to h2 </h1>
      
        <a href="{% url 'app2:func' %}">h1 navigates h2</a>
    
    </center>
    
</body>
</html>

templates/h2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>navigation h1 </h1>
        <h2><a href="{%  url 'h1' %}">h1 navigates h2</a></h2>
    
    </center>
    
</body>
</html>